export const SERVICE_DOWNTIME_UPDATE_REQUEST =
  "SERVICE_DOWNTIME_UPDATE_REQUEST";
export const SERVICE_DOWNTIME_UPDATE_SUCCESS =
  "SERVICE_DOWNTIME_UPDATE_SUCCESS";
export const SERVICE_DOWNTIME_UPDATE_FAIL = "SERVICE_DOWNTIME_UPDATE_FAIL";
export const SERVICE_DOWNTIME_UPDATE_RESET = "SERVICE_DOWNTIME_UPDATE_RESET";

export const SERVICE_DETAILS_REQUEST = "SERVICE_DETAILS_REQUEST";
export const SERVICE_DETAILS_SUCCESS = "SERVICE_DETAILS_SUCCESS";
export const SERVICE_DETAILS_FAIL = "SERVICE_DETAILS_FAIL";

export const SERVICE_LIST_REQUEST = "SERVICE_LIST_REQUEST";
export const SERVICE_LIST_SUCCESS = "SERVICE_LIST_SUCCESS";
export const SERVICE_LIST_FAIL = "SERVICE_LIST_FAIL";
